import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { initialCategories, products as initialProducts, type Product } from "@/data/products";
import { CatalogInputError } from "@/lib/catalog-errors";

type ProductRow = {
  id: number;
  slug: string;
  name: string;
  category: Product["category"];
  color: string;
  image: string;
  code: string;
  description: string;
  sizes: string[] | null;
  models: string[] | null;
};

const schemaSql = `
CREATE TABLE IF NOT EXISTS hatti_products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  color text NOT NULL,
  image text NOT NULL,
  code text NOT NULL,
  description text NOT NULL,
  sizes text[],
  models text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT hatti_products_options_check CHECK (sizes IS NULL OR models IS NULL)
);
CREATE TABLE IF NOT EXISTS hatti_media (
  filename text PRIMARY KEY,
  content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/webp')),
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS hatti_catalog_meta (
  key text PRIMARY KEY,
  value text NOT NULL
);
CREATE TABLE IF NOT EXISTS hatti_categories (
  name text PRIMARY KEY,
  sort_order integer NOT NULL
);
ALTER TABLE hatti_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE hatti_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE hatti_catalog_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE hatti_categories ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON hatti_products, hatti_media, hatti_catalog_meta, hatti_categories FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON hatti_products, hatti_media, hatti_catalog_meta, hatti_categories FROM authenticated;
  END IF;
END
$$;`;

let pool: Pool | undefined;
let schemaReady: Promise<void> | undefined;

export function databaseConfigured() {
  return Boolean(process.env.DATABASE_URL);
}

function getPool() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required for database storage.");
  if (!pool) {
    const url = new URL(process.env.DATABASE_URL);
    if (!['postgres:', 'postgresql:'].includes(url.protocol)) throw new Error("DATABASE_URL must use PostgreSQL.");
    const ca = process.env.DATABASE_SSL_CA_BASE64;
    pool = new Pool({
      host: url.hostname,
      port: Number(url.port || 5432),
      user: decodeURIComponent(url.username),
      password: decodeURIComponent(url.password),
      database: decodeURIComponent(url.pathname.slice(1)),
      max: 5,
      connectionTimeoutMillis: 10_000,
      idleTimeoutMillis: 30_000,
      ...(ca ? { ssl: { ca: Buffer.from(ca, "base64").toString("utf8"), rejectUnauthorized: true } } :
        process.env.DATABASE_SSL === "require" ? { ssl: { rejectUnauthorized: true } } : {}),
    });
  }
  return pool;
}

function toProduct(row: ProductRow): Product {
  return {
    id: row.id,
    slug: row.slug,
    name: row.name,
    category: row.category,
    color: row.color,
    image: row.image,
    code: row.code,
    description: row.description,
    ...(row.sizes?.length ? { sizes: row.sizes } : {}),
    ...(row.models?.length ? { models: row.models } : {}),
  };
}

async function initializeSchema() {
  const client = await getPool().connect();
  try {
    await client.query("BEGIN");
    await client.query("SELECT pg_advisory_xact_lock(1179804017)");
    await client.query(schemaSql);
    await client.query("ALTER TABLE hatti_products DROP CONSTRAINT IF EXISTS hatti_products_category_check");
    const categoriesSeeded = await client.query("SELECT 1 FROM hatti_catalog_meta WHERE key = 'categories_seed'");
    if (!categoriesSeeded.rowCount) {
      for (const [index, name] of initialCategories.entries()) {
        await client.query("INSERT INTO hatti_categories (name, sort_order) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING", [name, index]);
      }
      await client.query("INSERT INTO hatti_categories (name, sort_order) SELECT DISTINCT category, 100 FROM hatti_products ON CONFLICT (name) DO NOTHING");
      await client.query("INSERT INTO hatti_catalog_meta (key, value) VALUES ('categories_seed', 'done')");
    }
    await client.query(`DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'hatti_products_category_fkey') THEN
        ALTER TABLE hatti_products ADD CONSTRAINT hatti_products_category_fkey
          FOREIGN KEY (category) REFERENCES hatti_categories(name) ON UPDATE CASCADE ON DELETE RESTRICT;
      END IF;
    END $$`);
    const seeded = await client.query("SELECT 1 FROM hatti_catalog_meta WHERE key = 'initial_seed'");
    if (!seeded.rowCount) {
      const count = await client.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM hatti_products");
      if (count.rows[0].count === "0") {
        for (const product of initialProducts) {
          await client.query(
            `INSERT INTO hatti_products (id, slug, name, category, color, image, code, description, sizes, models)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
            [product.id, product.slug, product.name, product.category, product.color, product.image, product.code, product.description, product.sizes ?? null, product.models ?? null],
          );
        }
        await client.query("SELECT setval(pg_get_serial_sequence('hatti_products', 'id'), (SELECT MAX(id) FROM hatti_products), true)");
      }
      await client.query("INSERT INTO hatti_catalog_meta (key, value) VALUES ('initial_seed', 'done')");
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function database() {
  if (!schemaReady) schemaReady = initializeSchema().catch((error) => {
    schemaReady = undefined;
    throw error;
  });
  await schemaReady;
  return getPool();
}

export async function databaseProducts() {
  const result = await (await database()).query<ProductRow>(
    "SELECT id, slug, name, category, color, image, code, description, sizes, models FROM hatti_products ORDER BY id",
  );
  return result.rows.map(toProduct);
}

export async function databaseCategories() {
  const result = await (await database()).query<{ name: string }>("SELECT name FROM hatti_categories ORDER BY sort_order, name");
  return result.rows.map((row) => row.name);
}

export async function databaseCreateCategory(name: string) {
  const db = await database();
  const result = await db.query<{ name: string }>(
    "INSERT INTO hatti_categories (name, sort_order) VALUES ($1, (SELECT COALESCE(MAX(sort_order), -1) + 1 FROM hatti_categories)) ON CONFLICT (name) DO NOTHING RETURNING name",
    [name],
  );
  if (!result.rowCount) throw new CatalogInputError("Такая категория уже есть.");
}

export async function databaseRenameCategory(oldName: string, name: string) {
  const db = await database();
  const result = await db.query("UPDATE hatti_categories SET name=$2 WHERE name=$1 RETURNING name", [oldName, name]);
  if (!result.rowCount) throw new CatalogInputError("Категория не найдена.");
}

export async function databaseDeleteCategory(name: string) {
  const db = await database();
  const result = await db.query("DELETE FROM hatti_categories WHERE name=$1 AND NOT EXISTS (SELECT 1 FROM hatti_products WHERE category=$1) RETURNING name", [name]);
  if (!result.rowCount) throw new CatalogInputError("Категория не найдена или в ней есть товары. Сначала перенесите их в другую категорию.");
}

export async function databaseSaveProduct(id: number, input: Omit<Product, "id" | "slug">) {
  const result = await (await database()).query<ProductRow>(
    `UPDATE hatti_products SET name=$2, category=$3, color=$4, image=$5, code=$6, description=$7,
      sizes=$8, models=$9, updated_at=now() WHERE id=$1
     RETURNING id, slug, name, category, color, image, code, description, sizes, models`,
    [id, input.name, input.category, input.color, input.image, input.code, input.description, input.sizes ?? null, input.models ?? null],
  );
  if (!result.rows[0]) throw new CatalogInputError("Товар не найден.");
  return toProduct(result.rows[0]);
}

export async function databaseDeleteProduct(id: number) {
  const result = await (await database()).query("DELETE FROM hatti_products WHERE id=$1 RETURNING id", [id]);
  if (!result.rowCount) throw new CatalogInputError("Товар не найден.");
}

export async function databaseCreateProduct(input: Omit<Product, "id" | "slug">) {
  const result = await (await database()).query<ProductRow>(
    `INSERT INTO hatti_products (slug, name, category, color, image, code, description, sizes, models)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
     RETURNING id, slug, name, category, color, image, code, description, sizes, models`,
    [`product-${randomUUID()}`, input.name, input.category, input.color, input.image, input.code, input.description, input.sizes ?? null, input.models ?? null],
  );
  return toProduct(result.rows[0]);
}

export async function databaseSaveMedia(filename: string, contentType: string, bytes: Buffer) {
  await (await database()).query(
    "INSERT INTO hatti_media (filename, content_type, bytes) VALUES ($1, $2, $3)",
    [filename, contentType, bytes],
  );
}

export async function databaseReadMedia(filename: string) {
  const result = await (await database()).query<{ content_type: string; bytes: Buffer }>(
    "SELECT content_type, bytes FROM hatti_media WHERE filename=$1",
    [filename],
  );
  return result.rows[0] ?? null;
}
