CREATE TABLE IF NOT EXISTS hatti_products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL CHECK (category IN ('Футболки', 'Обложки', 'Чехлы', 'Кепки')),
  color text NOT NULL,
  image text NOT NULL,
  code text NOT NULL,
  description text NOT NULL,
  sizes text[],
  models text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT hatti_products_options_check CHECK (sizes IS NULL OR models IS NULL)
);

CREATE TABLE IF NOT EXISTS hatti_media (
  filename text PRIMARY KEY,
  content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/webp')),
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
