CREATE TABLE IF NOT EXISTS hatti_products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL CHECK (category IN ('Футболки', 'Обложки', 'Чехлы', 'Кепки')),
  color text NOT NULL,
  image text NOT NULL,
  code text NOT NULL,
  description text NOT NULL,
  sizes text[],
  models text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT hatti_products_options_check CHECK (sizes IS NULL OR models IS NULL)
);

CREATE TABLE IF NOT EXISTS hatti_media (
  filename text PRIMARY KEY,
  content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/webp')),
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hatti_catalog_meta (
  key text PRIMARY KEY,
  value text NOT NULL
);

ALTER TABLE hatti_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE hatti_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE hatti_catalog_meta ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON hatti_products, hatti_media, hatti_catalog_meta FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON hatti_products, hatti_media, hatti_catalog_meta FROM authenticated;
  END IF;
END
$$;
